#!/usr/bin/env python3
"""Not to be imported directly."""

import click

import fanghorn.main

app = None


@click.command()
@click.option('-h', '--hostname', default='127.0.0.1', show_default=True, help='Host for the server. Local only.')
@click.option('-p', '--port', default=8080, show_default=True, help='Port for the server. Local only.')
@click.option('-d', '--debugger', is_flag=True, help='Start server with debugger. Local only.')
@click.option('-r', '--reloader', is_flag=True, help='Start server with hot reloader. Local only.')
@click.option('--local', 'env', flag_value='local', default=True, show_default=True, help='Run in dev mode.')
@click.option('--prod', 'env', flag_value='prod', help='Run in prod mode. Provides an "app" object for a wsgi server.')
def main(hostname, port, reloader, debugger, env):
    """Create and optionally run the server."""
    global app
    app = fanghorn.main.get_app(env)
    if env == 'local':
        from werkzeug.serving import run_simple
        run_simple(hostname, port, app, use_reloader=reloader, use_debugger=debugger)


main()
