#!/usr/bin/env python3
from wsgiref import simple_server
import src.app


def main():
    app = src.app.get_app()

    httpd = simple_server.make_server('127.0.0.1', 8080, app)
    httpd.serve_forever()

if __name__ == '__main__':
    main()
