---
slack:
  outgoing_webhook:
    matchers:
      Build a PC Sales:
        text_contains:
          - "sennheiser"
          - "hd 598"
          - "[chair]"
        output_channel: "#general"
      logan:
        text_contains:
          - "passphrase"
        output_channel: "#general"
