---
slack:
  outgoing_webhook:
    matchers:
      Build a PC Sales:
        text_contains:
          - "ssd"
          - "hdd"
          - "xbox one"
          - "ultrawide"
        unmatch:
          - "laptop"
          - "[desktop]"
          - "pre built"
          - "pre-built"
          - "prebuilt"
          - "refurbish"
        output_channel: "#general"
      "FMF: Deals, Discussions, and Reviews":
        text_contains:
          - "red wing"
          - "filson"
          - "nordstrom"
        unmatch: []
        output_channel: "#general"
      logan:
        text_contains:
          - "passphrase"
        unmatch:
          - "unmatch"
        output_channel: "#general"
records:
  tinnitus:
    path: ~/records/tinnitus
google:
  static_map:
    url_base: https://maps.googleapis.com/maps/api/staticmap
    size:
      width: 400
      height: 200
    image_directory: '~/maps'
    path_format: weight:5|color:blue|enc:{}
    marker_format: size:mid|color:red|label:{}|{}
